version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DBUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${DBPASS}
    networks: 
      - mongo-client
      - dbnet
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DBUSER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DBPASS}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks: 
      - mongo-client
    depends_on: 
      - mongodb

  backend:
    stdin_open: true
    tty: true
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    env_file: 
      - ./config/.env
    networks: 
      - dbnet
    depends_on: 
      - mongodb

networks: 
  mongo-client:
    driver: bridge
  dbnet:
    driver: bridge
